### ISSUE TITLE
想问还有在继续开发嘛？

### ISSUE THREAD

**Issue by sheisloveyeah** [Bumblebee202111/doubean#1]
被官方客户端的广告淹没了，希望能够有一个好用的安卓客户端。看到这个项目的时候真的很惊喜！希望能继续完善呀～

**Comment by Bumblebee202111** [comment]
哇，这个练手项目居然被发现了，确实很久没维护了。当时写的代码不忍直视，而且功能残缺，连登录都没写。请问具体需要哪些界面和功能呢？我可以试着实现下。

**Comment by sheisloveyeah** [comment]
居然这么快就收到回复了，啊啊啊感谢！我稍微看了一下哦。现在的小组tab的话，评论里的图片似乎用了原分辨率显示？所以直接超出屏幕了哈哈哈，也无法点开查看。还有小组贴子正文中有投票和问答的没办法显示呢。比较希望能加强一下这两者呀。
主页tab应该是用来查看自己主页？提醒tab因为我大部分是潜水也不太用得到，如果可以用来显示关注人动态就太好啦。以上是比较希望能优先实现的功能。因为我对编程不太了解，就随心提了，还请按照自己的pace来～

**Comment by Bumblebee202111** [comment]
>居然这么快就收到回复了，啊啊啊感谢！

最近刚开始做 [WYYYY](https://github.com/Bumblebee202111/MinusOneMusic-public)，所以github用的比较勤。不用客气，我也是新手，做的app很烂。

>现在的小组tab的话，评论里的图片似乎用了原分辨率显示？所以直接超出屏幕了哈哈哈，也无法点开查看。

是的，当时偷懒了。可以加入to-do。

>还有小组贴子正文中有投票和问答的没办法显示呢。比较希望能加强一下这两者呀。

切换成网页模式即可查看。有需要的话可以做。

>主页tab应该是用来查看自己主页？

就是说想要登录功能吗？我没有了解过豆瓣的登录机制，是否有额外的保护与验证，但是我在隔壁app内已经实现了登录登出。

>提醒tab因为我大部分是潜水也不太用得到，

我也是潜水党，此tab目前是用来显示关注小组“推送”（实则本地主动获取）记录的，并且“推送”支持自定义。

>如果可以用来显示关注人动态就太好啦。

实现登录后如果官方有对应接口的话就简单了。

总：你也只需要用到小组模块，对吧？

***
开发豆瓣的话网络上可以参考的资源（如接口、第三方软件等）不像网易云一样丰富，并且自己现在使用得不多，也不是目前的开发重点，只能随缘进行了。不过有人提需求还是很开心的，会尽量满足的！

**Comment by sheisloveyeah** [comment]
哈哈哈哈谢谢呀！如果没有官方对应接口，其实只浏览也可以，不是太在意登录与否。不过如果不登录其实也就没必要有主页的tab了？感觉可以等优先了小组模块之后再研究登录～如果这样的话，能有一个没有空白tab页面的版本就好了～期待！

**Comment by sheisloveyeah** [comment]
手抖发送了没写完的comment还点到了comepleted，哈哈哈哈。苦豆瓣的广告还有臃肿的app久矣，期待能被拯救！

**Comment by Bumblebee202111** [comment]
朋友你好，今天打算开始动手了。需要你帮几个小忙：
- 回忆下或者用双开应用或备用机测试下密码登录是否会触发滑块验证。这玩意儿比较难绕过，已知验证码登录会触发。我这边想不起来自己的密码，并且担心找回密码并频繁测试登录后触发风控影响开发进度。
- 发我你的Android版本和系统名称以及最常用的三个界面截图，并且最好能看下你的主页（我豆瓣ID：231755795），为你量身定制。

以上信息可以豆瓣私信我或者发邮箱1264929989@qq.com，久等了！

**Comment by sheisloveyeah** [comment]
喜出望外！通过邮件发送啦，还请查收哦～

**Comment by Bumblebee202111** [comment]
[doubean_0.5.0-release.zip](https://github.com/Bumblebee202111/doubean/files/14996479/doubean_0.5.0-release.zip)

**Comment by Bumblebee202111** [comment]
![Uploading doubean_0.5.0-release.gif…]()

**Comment by Bumblebee202111** [comment]
[doubean_0.5.0-release.zip](https://github.com/Bumblebee202111/doubean/files/15022585/doubean_0.5.0-release.zip)
改后缀，不要解压
comment也有附件类型限制，觉得还是直接改后缀比较方便

**Comment by Bumblebee202111** [comment]
[Uploading doubean_0.5.0-release.zip…]()

**Comment by Bumblebee202111** [comment]
[doubean_0.5.1-release.zip](https://github.com/Bumblebee202111/doubean-public/files/15102204/doubean_0.5.1-release.zip)
